### ISSUE TITLE
[bazel on macOS] numpy: `incompatible architecture (have 'arm64', need 'x86_64')`

### ISSUE THREAD

**Issue by ubgk** [upkie/upkie#211]
When I run an agent with `bazel run`, the process fails with an error about incompatible numpy shared objects:

`'/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))`

My system **is** Apple silicon, yet numpy is complaining the `x86_64` build isn't there.

I can import `numpy` just fine when I launch Python:

```bash
❯ python3                                                                         
Python 3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> print(numpy.__file__)
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py
```

----
Full logs:
```
 ./tools/bazelisk run //agents/pid_balancer:pid_balancer
Using existing Bazel binary from /Users/bora/upkie/tools/bazel...
+ /Users/bora/upkie/tools/bazel version
Bazelisk version: v1.16.0
Bazelisk version: v1.16.0
Build label: 6.2.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 9 18:38:01 2023 (1683657481)
Build timestamp: 1683657481
Build timestamp as int: 1683657481
+ /Users/bora/upkie/tools/bazel run //agents/pid_balancer:pid_balancer
INFO: Analyzed target //agents/pid_balancer:pid_balancer (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //agents/pid_balancer:pid_balancer up-to-date:
  bazel-bin/agents/pid_balancer/pid_balancer
INFO: Elapsed time: 0.377s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/agents/pid_balancer/pid_balancer
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "/usr/local/bin/python3"
  * The NumPy version is: "1.26.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_bora/cd58d06b81b14a4ccab596e8d904b4af/execroot/upkie/bazel-out/darwin-opt/bin/agents/pid_balancer/pid_balancer.runfiles/upkie/agents/pid_balancer/main.py", line 16, in <module>
    from servo_controller import ServoController
  File "/private/var/tmp/_bazel_bora/cd58d06b81b14a4ccab596e8d904b4af/execroot/upkie/bazel-out/darwin-opt/bin/agents/pid_balancer/pid_balancer.runfiles/upkie/agents/pid_balancer/servo_controller.py", line 9, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by stephane-caron** [comment]
I noticed @pgraverdy added a ``darwin_arm64`` configuration in ``.bazelrc``. Maybe you want to run your agent with that config?

```sh
./tools/bazelisk run --config=<config_name>
```

**Comment by stephane-caron** [comment]
Sounds good, open a PR if you feel like taking a stab at it :+1:

**Comment by pgraverdy** [comment]
Compiled and rlaunched Bullet spine + PID balancer on my M2 just fine (Sonoma 14.1).
`arch` command returns arm64 in the terminal.
